apiVersion: apps/v1
kind: Deployment
metadata:
  name: vineeth-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vineeth
  template:
    metadata:
      labels:
        app: vineeth
    spec:
      containers:
      - name: vineeth-container
        image: vineeth-demo
        imagePullPolicy: Never
        ports:
        - containerPort: 80
